server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/order_db}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        interceptor.classes: com.onlinestore.order.tracing.KafkaProducerInterceptor
        spring.json.type.mapping: orderCreated:com.onlinestore.order.kafka.OrderCreatedEvent

# gRPC Configuration
grpc:
  client:
    inventory-service:
      address: static://${GRPC_CLIENT_INVENTORY_SERVICE_ADDRESS:localhost:9090}  # Inventory Service gRPC port
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-timeout: 10s
      max-inbound-message-size: 4194304  # 4M

# JWT Configuration
jwt:
  secret: "your-256-bit-secret-change-this-in-production-minimum-32-chars"
  expiration: 86400000  # 24 hours in milliseconds


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-NO_TRACE}] [%X{spanId:-NO_SPAN}] [%X{parentSpanId:-NO_PARENT_SPAN}] %-5level [%thread] %logger{36} - %msg%n"
  level:
    com.onlinestore.order: TRACE
    org.springframework.security: WARN
    org.springframework.kafka: WARN
